spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/user/**

        - id: pay-service
          uri: http://localhost:8085
          predicates:
            - Path=/pay/**
server:
  port: 8088
